import { createAction, createActions } from 'redux-actions';

const FETCH_COMPANY_LOGO = 'FETCH_COMPANY_LOGO';
const FETCH_COMPANY_LOGO_SUCCESS = 'FETCH_COMPANY_LOGO_SUCCESS';
const FETCH_COMPANY_LOGO_ERROR = 'FETCH_COMPANY_LOGO_ERROR';
const FETCH_COMPANY_LOGO_RESET = 'FETCH_COMPANY_LOGO_RESET';

const companyLogoActions = createActions(
  FETCH_COMPANY_LOGO,
  FETCH_COMPANY_LOGO_SUCCESS,
  FETCH_COMPANY_LOGO_ERROR,
  FETCH_COMPANY_LOGO_RESET
);

export default companyLogoActions;

export {
  FETCH_COMPANY_LOGO,
  FETCH_COMPANY_LOGO_SUCCESS,
  FETCH_COMPANY_LOGO_ERROR,
  FETCH_COMPANY_LOGO_RESET,
};
