const MAIN_BACKGROUND_COLOR = '#000000';
const DRAWER_BUTTON_COLOR = '#565454';
const SEARCH_INPUT_COLOR = '#d1d1d1';
const BORDER_BOTTOM = '#555252';

export { MAIN_BACKGROUND_COLOR, DRAWER_BUTTON_COLOR, SEARCH_INPUT_COLOR, BORDER_BOTTOM };
